---
title: "example1"
author: "Alexia Cardona"
date: "2022-12-01"
output: html_document
---

The sdkfsdlfsfj

# This is a header

```{r load-data, message=FALSE}
library(tidyverse)
library(kableExtra)
library(rmarkdown)

# This is a comment
# Load the dataset 
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 showing the countries
# with the largest life expectancy on top
euro_data_tbl <- pop_data %>%
                    filter(continent == "Europe" & year == 2007) %>%
                    select(-continent, -year) %>%
                    arrange(desc(lifeExp)) %>%
                    rename("Country" = country, "Population Size" = pop, 
                           "Life Expectancy" = lifeExp, "GDP"=gdpPercap)


```
here we have our data set...

```{r create-table}
euro_data_tbl %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

Here is an example of how to display a massive table

```{r paged-table}
paged_table(euro_data_tbl)
```



